services:

  # Backend: NodeJS + Express
  backend:
    image: manishjangradev/todo-app-backend
    container_name: todo-backend
    environment:
      - DB_HOST=mysql-db
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - my-sql-networks

  # Frontend: ReactJS
  frontend:
    image: manishjangradev/todo-app-frontend
    container_name: todo-frontend
    ports:
      - "80:80"
    env_file:
      - ./frontend/.env
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - my-sql-networks

  # Database: MYSQL
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-sql-networks

volumes:
  db_data:
    name: db_data

networks:
  my-sql-networks:
    driver: bridge
    name: my-sql-networks
