services:

# Reverse Proxy: Nginx 
  nginx:
    image: nginx:stable-alpine
    container_name: todo-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - frontend
      - backend
    networks:
      - my-sql-networks

# Backend: NodeJS + Express
  backend:
    image: manishjangradev/todo-app-backend
    container_name: todo-backend
    environment:
      - DB_HOST=${MYSQL_HOST}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - DB_NAME=${MYSQL_DATABASE}
    depends_on:
      mysql-db:
        condition: service_healthy
    restart: unless-stopped
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - my-sql-networks

  # Frontend: ReactJS
  frontend:
    image: manishjangradev/todo-app-frontend
    container_name: todo-frontend
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - my-sql-networks

  #  Database: MYSQL
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my-sql-networks
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  # Monitoring: Prometheus
  # prometheus:
  #   image: prom/prometheus
  #   volumes:
  #     - ./prometheus.yml:/etc/prometheus/prometheus.yml
  #   networks:
  #     - my-sql-networks

  # # Monitoring: Grafana Dashboard
  # grafana:
  #   image: grafana/grafana
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - my-sql-networks

  # # Resource Usage Collector
  # cadvisor:
  #   image: gcr.io/cadvisor/cadvisor:latest
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - /:/rootfs:ro
  #     - /var/run:/var/run:ro
  #     - /sys:/sys:ro
  #     - /var/lib/docker/:/var/lib/docker:ro
  #   networks:
  #     - my-sql-networks

volumes:
  db_data:
    name: db_data

networks:
  my-sql-networks:
    driver: bridge
    name: my-sql-networks
