# global:
#   scrape_interval: 15s # Har 15 second mein data collect karega

# scrape_configs:
#   # 1. Prometheus khud ka data
#   - job_name: 'prometheus'
#     static_configs:
#       - targets: ['localhost:9090']

#   # 2. Docker Containers ka data (via cAdvisor)
#   - job_name: 'cadvisor'
#     static_configs:
#       - targets: ['cadvisor:8080']

#   # 3. Node.js Backend ka data (Agar aapne metrics expose kiye hain)
#   - job_name: 'backend'
#     static_configs:
#       - targets: ['backend:5000']